Document: gtknode
Title: Debian gtknode Manual
Author: <insert document author here>
Abstract: This manual describes what gtknode is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gtknode/gtknode.sgml.gz

Format: postscript
Files: /usr/share/doc/gtknode/gtknode.ps.gz

Format: text
Files: /usr/share/doc/gtknode/gtknode.text.gz

Format: HTML
Index: /usr/share/doc/gtknode/html/index.html
Files: /usr/share/doc/gtknode/html/*.html
